import { Scholarship } from "@/types";

export const scholarships: Scholarship[] = [
  { id: "gates", name: "Gates Scholarship", amount: "Full ride", deadline: "September 15", description: "Full cost of attendance for exceptional, Pell-eligible minority students.", tags: ["need-based", "first-gen"], url: "#" },
  { id: "questbridge", name: "QuestBridge National College Match", amount: "Full ride", deadline: "September 27", description: "Links high-achieving, low-income students with full four-year scholarships to top colleges.", tags: ["need-based", "first-gen"], url: "#" },
  { id: "coca-cola", name: "Coca-Cola Scholars Program", amount: "$20,000", deadline: "October 31", description: "For high school seniors with strong leadership and community service.", tags: ["merit"], url: "#" },
  { id: "regeneron", name: "Regeneron Science Talent Search", amount: "Up to $250,000", deadline: "November 15", description: "The nation's most prestigious pre-college science and math competition.", tags: ["merit", "STEM"], url: "#" },
  { id: "davidson", name: "Davidson Fellows Scholarship", amount: "Up to $50,000", deadline: "February 12", description: "For students 18 and under who have completed a significant piece of work in STEM, literature, or music.", tags: ["merit", "STEM", "arts"], url: "#" },
  { id: "jack-kent", name: "Jack Kent Cooke Foundation", amount: "Up to $55,000/year", deadline: "November 15", description: "For high-achieving students with financial need transferring from community college.", tags: ["need-based", "merit"], url: "#" },
  { id: "elks", name: "Elks Most Valuable Student", amount: "Up to $60,000", deadline: "November 5", description: "Based on scholarship, leadership, and financial need.", tags: ["need-based", "merit"], url: "#" },
  { id: "buick", name: "Buick Achievers Scholarship", amount: "Up to $100,000", deadline: "February 28", description: "For students interested in STEM fields who demonstrate financial need.", tags: ["STEM", "need-based"], url: "#" },
  { id: "dell", name: "Dell Scholars Program", amount: "$20,000", deadline: "December 1", description: "For underprivileged students who demonstrate a drive to succeed.", tags: ["need-based", "first-gen"], url: "#" },
  { id: "horatio-alger", name: "Horatio Alger Scholarship", amount: "$25,000", deadline: "October 25", description: "For students who have overcome great adversity.", tags: ["need-based"], url: "#" },
  { id: "ron-brown", name: "Ron Brown Scholar Program", amount: "$40,000", deadline: "January 9", description: "For African American high school seniors who demonstrate academic excellence and leadership.", tags: ["merit", "first-gen"], url: "#" },
  { id: "cameron-impact", name: "Cameron Impact Scholarship", amount: "$50,000", deadline: "September 14", description: "For students who demonstrate excellence in academics, extracurriculars, and community service.", tags: ["merit"], url: "#" },
  { id: "goldwater", name: "Barry Goldwater Scholarship", amount: "$7,500/year", deadline: "January 27", description: "For college sophomores and juniors pursuing STEM research careers.", tags: ["merit", "STEM"], url: "#" },
  { id: "scholastic", name: "Scholastic Art & Writing Awards", amount: "Up to $10,000", deadline: "December varies", description: "The nation's longest-running and most prestigious recognition program for creative teens.", tags: ["arts", "merit"], url: "#" },
  { id: "youngarts", name: "YoungArts Foundation", amount: "Up to $10,000", deadline: "October 11", description: "For emerging artists ages 15-18 in visual, literary, and performing arts.", tags: ["arts", "merit"], url: "#" },
  { id: "siemens", name: "Siemens Competition", amount: "Up to $100,000", deadline: "September 20", description: "For high school students who have undertaken individual or team research projects in STEM.", tags: ["STEM", "merit"], url: "#" },
  { id: "davis-putter", name: "Davis-Putter Scholarship", amount: "$15,000", deadline: "April 1", description: "For students active in movements for social and economic justice.", tags: ["need-based"], url: "#" },
  { id: "cobell", name: "Cobell Scholarship", amount: "Up to $5,000", deadline: "February varies", description: "For Native American students pursuing post-secondary education.", tags: ["need-based", "first-gen"], url: "#" },
  { id: "daniels", name: "Daniels Fund Scholarship", amount: "Full ride", deadline: "November 15", description: "For students in CO, NM, UT, WY who demonstrate character and leadership.", tags: ["need-based", "merit"], url: "#" },
  { id: "posse", name: "Posse Foundation", amount: "Full tuition", deadline: "Nomination-based", description: "Identifies public high school students with extraordinary academic and leadership potential.", tags: ["merit", "first-gen"], url: "#" },
];
